In [353]:
import requests

url = 'https://es.wikipedia.org/wiki/Copa_Mundial_de_F%C3%BAtbol_de_2018'
html = requests.get(url).content

In [245]:
from bs4 import BeautifulSoup
import pandas as pd

soup = BeautifulSoup(html, "lxml")

#Get teams
teams = [e.text.strip() for e in soup.select('.vevent tbody td[width="22%"]')]
#Filter local teams
localTeams = teams[0::2]
#Get local goals
goals = [int(e.text.strip()[0]) for e in soup.select('.vevent tbody td[width="12%"]')]

localGoals = {}

# match local teams with goals
for index in range(0, len(localTeams)):
    if localTeams[index] in localGoals:
        localGoals[localTeams[index]] += goals[index]
    else:
        localGoals[localTeams[index]] = goals[index]

# sort by goals
sortedGoals = sorted(localGoals.items(), key=lambda elem: elem[1], reverse=True)

# print table
pd.DataFrame(sortedGoals, columns=["Team","Goals"])

              Team  Goals
0          Bélgica     13
1          Francia     12
2            Rusia     10
3          Uruguay      6
4           Brasil      6
5       Inglaterra      6
6          Croacia      5
7         Portugal      4
8           España      3
9          Nigeria      3
10   Corea del Sur      3
11  Arabia Saudita      2
12           Suiza      2
13        Alemania      2
14          Suecia      2
15        Colombia      2
16           Japón      2
17            Irán      1
18       Dinamarca      1
19       Argentina      1
20        Islandia      1
21          Serbia      1
22           Túnez      1
23          Panamá      1
24         Polonia      1
25          Egipto      0
26       Marruecos      0
27            Perú      0
28       Australia      0
29      Costa Rica      0
30          México      0
31         Senegal      0

In [351]:
import re
players = [ e.text.strip()
           .replace("(pen.),", ",")
           .replace("(pen.)", "\n")
           .replace("(a.g.)", "(a.g.)\n") for e in soup.select('td[align="right"]')]
#get only goals, not teams
players = filter(lambda elem: '\'' in elem,players)

#split player from other players
playersSplit = []
for elem in players:
    a = re.split("\'[A-Z]", elem)
    for player in a:
        if(player.count('(a.g.)') == 0):
            playersSplit.append(player)


playerGoal = {}
for i in playersSplit:
    tmp = i.split(" ")[0]
    if tmp in playerGoal:
        playerGoal[tmp] += i.count(',')+1
    else:
        playerGoal[tmp] = i.count(',')+1
        
sortedPlayerGoals = sorted(playerGoal.items(), key=lambda elem: elem[1], reverse=True)
pd.DataFrame(sortedPlayerGoals, columns=["Player","Goals"])

        Player  Goals
0      Ronaldo      4
1        ukaku      4
2          ane      3
3        bappé      3
4     héryshev      2
5        ziuba      2
6       Suárez      2
7         Musa      2
8     Coutinho      2
9       Hazard      2
10      Stones      2
11      Cavani      2
12    Gazinski      1
13      olovín      1
14    Al-Faraj      1
15  Ansarifard      1
16        Isco      1
17        spas      1
18     Eriksen      1
19      Mbappé      1
20      Agüero      1
21       Moses      1
22  Sigurðsson      1
23       eymar      1
24    Mitrović      1
25    Džemaili      1
26        rmić      1
27   Granqvist      1
28          H.      1
29        Reus      1
30        roos      1
31          Y.      1
32           .      1
33     Mertens      1
34       Sassi      1
35    atshuayi      1
36      ingard      1
37    Quintero      1
38  Krychowiak      1
39        Inui      1
40        onda      1
41   Griezmann      1
42   Mandžukić      1
43      Neymar      1
44      irmino      1
45  Vertonghen      1
46     ellaini      1
47       hadli      1
48    Forsberg      1
49        Mina      1
50      Renato      1
51   Chéryshev      1
52    ernandes      1
53      Umtiti      1
54     Perišić      1
55    andžukić      1
56     Meunier      1
57       azard      1

In [289]:
#Get final rounds goals
finalRoundGoals = goals[-16::2]
avgFinalGoals = sum(finalRoundGoals)/len(finalRoundGoals)
    
print(str(avgFinalGoals) + ' average goals per match above quarter finals')

1.125 average goals per match above quarter finals